version: '3'  # Adding a version is helpful

services:
  # nginx 
  nginx:
    container_name: nginx
    build:
      context: ./backend/proxy-server
      dockerfile: Dockerfile
    ports:
      - 80:80
    networks:
      - ecosystem
    depends_on:
      - auth
      - course
      - lesson
      - email
      - web

  # Updated frontend service
  web:
    container_name: web
    build: 
      context: ./frontend/master-course
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      VITE_API_URL: http://nginx:80 # Using nginx as the API gateway
    networks:
      - ecosystem
    depends_on:
      - auth
      - course
      - lesson
    volumes:
      - ./frontend/master-course:/app
      - /app/node_modules

  # Authentication service
  auth:
    container_name: auth
    build: ./backend/authentication-service
    ports:
      - 8001:8001
    environment:
      # DB_URL: mongodb://localhost:27017/anime
      JWT_SECRET: 357c546c-d674-41b9-a5cd-a2bc2c9f5ac5
      PORT: 8001
    networks:
      - ecosystem

  # Course service
  course:
    container_name: course
    build: ./backend/course-service
    ports:
      - 8002:8002
    environment:
      # DB_URL: mongodb://localhost:27017/anime
      JWT_SECRET: 357c546c-d674-41b9-a5cd-a2bc2c9f5ac5
      PORT: 8002
    networks:
      - ecosystem

  # Lesson service
  lesson:
    container_name: lesson
    build: ./backend/lesson-service
    ports:
      - 8003:8003
    environment:
      # DB_URL: mongodb://localhost:27017/anime
      JWT_SECRET: 357c546c-d674-41b9-a5cd-a2bc2c9f5ac5
      PORT: 8003
    networks:
      - ecosystem

  # Email service
  email:
    container_name: email
    build: ./backend/email-service
    ports:
      - 8004:8004
    environment:
      # DB_URL: mongodb://localhost:27017/anime
      JWT_SECRET: 357c546c-d674-41b9-a5cd-a2bc2c9f5ac5
      PORT: 8004
    networks:
      - ecosystem

  # Enrollment service
  enroll:
    container_name: enroll
    build: ./backend/enrollement-service
    ports:
      - 8011:8011
    environment:
      # DB_URL: mongodb://localhost:27017/anime
      JWT_SECRET: 357c546c-d674-41b9-a5cd-a2bc2c9f5ac5
      PORT: 8011
    networks:
      - ecosystem

networks:
  ecosystem:
    driver: bridge

volumes:
  mongo_data: