name: Trigger auto deployment for course-service

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/course-service-AutoDeployTrigger-c69c0676-5636-4235-860b-0092b4e744ac.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.COURSESERVICE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.COURSESERVICE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.COURSESERVICE_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: 
          registryUsername: ${{ secrets.COURSESERVICE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.COURSESERVICE_REGISTRY_PASSWORD }}
          containerAppName: course-service
          resourceGroup: ctsemicro
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


