name: Course CI/CD
on:
  push:
    branches:
      - main  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/course-service:latest ./backend/course-service

      - name: Login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Push Image
        run: docker push ${{ secrets.ACR_LOGIN_SERVER }}/course-service:latest

      # Add this Azure login step before the deployment step
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure
        uses: azure/container-apps-deploy-action@v1
        with:
          appName: course-service  # Make sure app-name is specified
          imageToDeploy: ${{ secrets.ACR_LOGIN_SERVER }}/course-service:latest
          resourceGroup: ${{ secrets.AZURE_RESOURCE_GROUP }}
          registryUrl: ${{ secrets.ACR_LOGIN_SERVER }}  # Fixed parameter name
          registryUsername: ${{ secrets.ACR_USERNAME }}  # Fixed parameter name
          registryPassword: ${{ secrets.ACR_PASSWORD }}  # Fixed parameter name
          targetPort: 8002
          ingress: external