name: Course Service CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/course-service/**'
      - '.github/workflows/course-service.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/course-service/**'

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: backend/course-service/package-lock.json
    
    - name: Install dependencies
      run: cd backend/course-service && npm ci
    
    # Security scan with Snyk (DevSecOps)
    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/node@master
      continue-on-error: true
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: --file=backend/course-service/package.json
    
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    
    - name: Build and push Docker image
      run: |
        cd backend/course-service
        docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/course-service:${{ github.sha }} .
        docker tag ${{ secrets.ACR_LOGIN_SERVER }}/course-service:${{ github.sha }} ${{ secrets.ACR_LOGIN_SERVER }}/course-service:latest
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/course-service:${{ github.sha }}
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/course-service:latest
    
    - name: Deploy Course Service
      uses: azure/CLI@v1
      with:
        inlineScript: |
          # Create new container app
          az containerapp create \
            --name course-service \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --environment master-learn-env \
            --image ${{ secrets.ACR_LOGIN_SERVER }}/course-service:${{ github.sha }} \
            --registry-server ${{ secrets.ACR_LOGIN_SERVER }} \
            --registry-username ${{ secrets.ACR_USERNAME }} \
            --registry-password "${{ secrets.ACR_PASSWORD }}" \
            --target-port 8002 \
            --ingress external \
            --env-vars "PORT=8002" "JWT_SECRET=357c546c-d674-41b9-a5cd-a2bc2c9f5ac5" "MONGODB_URI=mongodb+srv://yourusername:yourpassword@cluster.mongodb.net/yourdb"