name: Trigger auto deployment for course-service

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/course-service-AutoDeployTrigger-85b3385c-c5b6-49b6-9bcc-4d95dea27ec2.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.COURSESERVICE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.COURSESERVICE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.COURSESERVICE_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}backend/course-service
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: microctseregistry.azurecr.io
          registryUsername: ${{ secrets.COURSESERVICE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.COURSESERVICE_REGISTRY_PASSWORD }}
          containerAppName: course-service
          resourceGroup: microctse
          imageToBuild: microctseregistry.azurecr.io/course-service:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


